l_english:
 SETTING_INPUT_CONTEXT_COMMON:0 "Common"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Keybinds for the common input context"

 SETTING_INPUT_ACTION_PAUSE:0 "Pause / Unpause"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Increase Speed"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Decrease Speed"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Speed 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Speed 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Speed 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Speed 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Speed 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Play/Pause Music"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Next Music track"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Pan Camera Up"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Pan Camera Left"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Pan Camera Down"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Pan Camera Right"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Location Finder"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Politics"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Budget"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Buildings"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Market"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Military"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomatic"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Technology"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Society"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Population"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Journal"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Power Bloc"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Companies"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Ledger"
 SETTING_INPUT_ACTION_BACK:0 "Back"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Outliner"
 SETTING_INPUT_ACTION_TAB_1:0 "Tab 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Tab 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Tab 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Tab 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Tab 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Production Lens"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Political Lens"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Diplomatic Lens"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Military Lens"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Trade Lens"
 SETTING_INPUT_ACTION_CONFIRM:0 "Confirm"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Current Situation"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "Construction Queue"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Pause/Unpause Construction Queue"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Go to Details"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Scroll up"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Scroll down"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Show Pinned in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Show Economy in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Show Politics in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Show Diplomacy in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Show Military in Outliner" 
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Show All in Outliner" 
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Toggle Pin"
 SETTING_INPUT_ACTION_ZOOM_TO: "Zoom To"
