l_english:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Autosave to cloud"
 SETTING_SAVE_FILE_FORMAT:0 "Default save format"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "This option is overridden in Ironman, Cloud, and Debug mode"
 OPTION_SAVE_FILE_TEXT:0 "Text"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Zipped text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Zipped binary"
 SETTING_TOOLTIP_MODE:0 "Tooltip Mode"
 SETTING_TOOLTIP_MODE_TOOLTIP:2 "#T $SETTING_TOOLTIP_MODE$#!\nChoose how the tooltips should lock:\n   #b Mouse Tendency#! - Locks it if you move the mouse towards the tooltip.\n   #b Timer Lock#! - Locks it after a set time.\n   #b Action Lock#! - Locks it with middle mouse button.\n   #b Timer Or Action Lock#! - Can use either Timer Lock or Action Lock."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "No lock"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse Tendency"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Action Lock ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Timer Lock ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Timer Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Timer Or Action Lock"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before the tooltip shows up when hovering an element with a tooltip."
 SETTING_TOOLTIP_DELAY:0 "Show Delay"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Unlock Delay"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "Lock Delay"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Advanced"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "General"
 SETTINGS_CATEGORY_SFX:1 "Sound Effects"
 SETTINGS_CATEGORY_MFX:0 "Music"
 SETTINGS_CATEGORY_LANGUAGE:0 "Language"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Save Games"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Tooltip Settings"
 SETTINGS_CATEGORY_OUTLINER:0 "Outliner"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Map Controls"
 SETTINGS_CATEGORY_MAPMODES:0 "Map Modes"
 SETTING_SHADER_QUALITY:0 "Shader Quality"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Shader Quality\n#!Determines the quality of various shaders and effects.\n\n#T High:#! Improves quality of some shader effects at the cost of performance.\n\n#T Medium:#! Default setting for the intended graphical experience.\n\n#T Low:#! This setting is made for low-end machines and is not recommended due to the loss in visual quality. Multiple shaders are simplified to push graphical performance."
 SETTING_SHOW_NUDITY:0 "Show Nudity"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 
 SETTING_PAUSE_ON_EVENT: "Pause and Popup on Events"
 SETTING_PAUSE_ON_EVENT_TOOLTIP: "#T $SETTING_PAUSE_ON_EVENT$#!\nPauses the game and shows the popup when an event is triggered."
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS: "Notifications"
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS: "$SETTING_PAUSE_ON_EVENT$ (Single player only)"

 SETTING_VALUE_HOURS: "$VALUE|0$ Hours"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"

 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Day night cycle"
 SETTING_DAYNIGHT_CYCLE: "Enable day night cycle"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nEnables a day and night cycle for the sun movement."
 SETTING_DAYNIGHT_SYSTEMTIME: "Enable sync local time"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSyncronizes the day night cycle speed and time to the computers local time.\n\n#!Will override simulation speed setting."
 SETTING_DAYNIGHT_SPEED: "Simulation Speed"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nHow fast the time will cycle between day and night.#"
 SETTING_SUN_DURATION: "Sun hours"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nThe amount of hours of sun in a day."
 SETTING_SUNRISE_TIME: "Time of sunrise"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nThe hour the sun will rise.\n\n#!Only used when synced with local time. #!"
 SETTING_DAYNIGHT_SET_TIME: "Enable manual time"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nSets time of day to a specified hour.\n\n#!Will override simulation speed and sync local time settings."
 SETTING_SUNRISE_SET_TIME_HOUR: "Manual time hour"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nLocks the time to this hour.\n\n#!Only used when manual time is enabled#"

 SETTING_BUILDINGS_CUTOFF:1 "Cull Distant Buildings"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP:1 "#T $SETTING_BUILDINGS_CUTOFF$#!\nShow fewer buildings on the map, the further away they are from the camera.\n\nTurning it on may increase performance."

 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Notifications to the left of Outliner"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nPlace the Notifications Feed to the left of the Outliner"

 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portraits"
 SETTING_SOUNDTRACK:0 "Background Music"
 SETTING_SOUNDTRACK_TOOLTIP:0 "General background music"
 SETTING_MUSIC_STINGERS:0 "Music Stingers"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "Short musical phrases to enhance gameplay"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Music"
 SETTING_AMBIENT:0 "Ambient"
 SETTING_MUSIC_TOOLTIP:0 "#T Music Volume\n#!Sets the volume of the music."
 SETTING_AMBIENT_TOOLTIP:0 "#T Ambient Volume\n#!Sets the volume of environmental ambience."

 SETTING_MAP_TOOLTIP_DELAY:0 "Map Tooltip Delay"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nSets the delay before the map tooltip is shown."

 SETTING_MAP_MODE_DELAY:0 "Mapmode Delay"
 SETTING_MAP_MODE_DELAY_TOOLTIP:0 "Delay before switching to a new Mapmode, in seconds"
 SETTING_MAP_MODE_FADE_IN:0 "Mapmode Fade-in"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP:0 "Time for a new Mapmode to fade-in after the old has faded out, in seconds"
 SETTING_MAP_MODE_FADE_OUT:0 "Mapmode Fade-out"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP:0 "Time for the current Mapmode to fade-out after the Mapmode Delay when a new Mapmode is to be applied, in seconds"

 SETTING_OCCUPATION_STRIPES: "Striped Occupation Visuals"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nEnable colored stripes as occupation visuals on the map instead of country flag textures"

 SETTING_PORTRAIT_RENDER_SCALE: "Portrait Render Scaling"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nImprove character portrait detail level by upscaling render results, at the cost of some more rendering performance."

 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1.0 - None"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1.5 - Medium"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2.0 - High"

 ui_skin_theme: "User Interface"
 ui_skin_theme_desc: "The buttons, frames, windows, headers, etc. in the game."
 papermap_theme: "Paper Map"
 papermap_theme_desc: "This is the map you see when you are zoomed out."
 table_top_theme: "Table Top"
 table_top_theme_desc: "If you zoom out as far as you can on the map, you can see this table on the top and bottom of your screen."
 table_asset_1_theme: "Table Object (top left)"
 table_asset_1_theme_desc: "The object displayed in the top left of the table next to the map when zoomed out."
 table_asset_2_theme: "Table Object (top right)"
 table_asset_2_theme_desc: "The object displayed in the top right of the table next to the map when zoomed out."
 table_asset_3_theme: "Table Object (bottom left)"
 table_asset_3_theme_desc: "The object displayed in the bottom left of the table next to the map when zoomed out."
 table_asset_4_theme: "Table Object (bottom right)"
 table_asset_4_theme_desc: "The object displayed in the bottom right of the table next to the map when zoomed out."
 table_asset_cloth_theme: "Table Cloth"
 table_asset_cloth_theme_desc: "The cloth which the coins are resting on."
 building_sets_themes: "Building Set"

 color_blind_mode_test:0 "Test"
