l_japanese:
 SETTINGS_PAGE_GRAPHICS: "グラフィック"
 SETTINGS_PAGE_GAME: "ゲーム"
 SETTINGS_PAGE_SYSTEM: "システム"
 SETTINGS_PAGE_CONTROLS: "コントロール"
 SETTINGS_PAGE_EDITOR: "エディター"
 SETTINGS_PAGE_INTERFACE: "インターフェイス"
 SETTINGS_PAGE_AUDIO: "オーディオ"
 SETTINGS_CATEGORY_SCREEN: "スクリーン"
 SETTINGS_CATEGORY_QUALITY: "品質"
 OPTION_EASY: "イージー"
 OPTION_NORMAL: "ノーマル"
 OPTION_HARD: "ハード"
 OPTION_NEVER: "ない"
 OPTION_MONTHLY: "毎月"
 OPTION_HALFYEAR: "半年に1度"
 OPTION_YEARLY: "毎年"
 OPTION_FIVE_YEAR: "5年に1度"
 OPTION_NO_AUTOSAVE: "自動セーブしない"
 SETTINGS_CATEGORY_ACCOUNT: "アカウント"
 SETTINGS_CATEGORY_SYSTEM: "システム"
 SETTINGS_CATEGORY_CONTROLS: "コントロール"
 SETTINGS_CATEGORY_CAMERA: "カメラ"
 SETTINGS_CATEGORY_AUDIO: "オーディオ"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "入力バインディング"
 DISCARD: "破棄"
 APPLY: "適用"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "設定"
 REQUIRES_RESTART: "再起動が必要です"
 REQUIRE_RESTART_DESCRIPTION: "ゲームを再起動するまで一部の設定は適用されません"
 SETTINGS_INPUT_REMAP_INPUT: "再マップ入力"
 SETTINGS_INPUT_CONFIRM: "確認"
 SETTINGS_INPUT_CANCEL: "キャンセル"
 SETTINGS_INPUT_CLEAR: "消去"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "プロフィールを保存"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "プロフィールをロード"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "デフォルトにリセット"
 SETTINGS_INPUT_BINDING_TEXT: "'$INPUT_ACTION$' アクションの入力バインディングを選択してください: \n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "警告: この入力バインディングは '$INPUT_ACTION$' にすでに存在しています！\n'$SETTINGS_INPUT_CONFIRM$' を押すと古いバインディングを消去します"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "警告：入力バインディングはモディファイアキーのみでは構成できません"
 SETTINGS_PAGE_ACCOUNT: "アカウント"
 SETTING_TELEMETRY_CONSENT: "テレメトリデータを送信（任意）"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T データ送信の同意#!\n任意のテレメトリデータをParadox Interactiveに送信することを許可します。"
