l_japanese:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$秒"
 SETTING_VALUE_MINUTES: "$VALUE$分"
 #Graphics
 SETTING_RENDERER: "レンダラー"
 SETTING_RENDERER_TOOLTIP: "どのレンダラーが使用されているかを判断します。"
 SETTING_VSYNC: "垂直同期"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!ゲームとモニターのフレームレートを合わせることで画面のティアリングを抑制します。\n\nオフにするとパフォーマンスが向上する場合があります。"
 SETTING_PORTRAIT_MULTI_SAMPLING: "肖像マルチサンプリング"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Alpha To Coverageにはマルチサンプリングを使用し、髪の毛のブレンディングをよりなめらかにします。\n\n低く設定するとパフォーマンスが向上します。"
 SETTING_MULTI_SAMPLING: "アンチエイリアス（MSAA）"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!マルチサンプルアンチエイリアス（MSAA）はイメージの輪郭をよりなめらかにします。\n\n低く設定するとパフォーマンスが向上します。"
 SETTING_ANTI_ALIASING: "アンチエイリアス"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!アンチエイリアスはイメージの輪郭をよりなめらかにします。\n\nFXAAを推奨します。"
 OPTION_ANTI_ALIASING_DISABLED: "無効"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "アップスケーリング"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nアップスケーリングを使用すると、アルゴリズムによるアップサンプリングによってより高い画面解像度を得ることができます。これによりパフォーマンスが改善されることがありますが、視覚的アーティファクトやその他の予期せぬ挙動が発生する可能性があります。\n\n利用可能なアップスケーリングはお使いのグラフィックカードによって異なります。"
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "アップスケーリング品質"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nアップスケーリングの目標を最高品質から最高パフォーマンスの間で設定します。"
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "ウルトラクオリティ"
 OPTION_UPSCALE_QUALITY_QUALITY: "クオリティ"
 OPTION_UPSCALE_QUALITY_BALANCED: "バランス"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "パフォーマンス"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "ウルトラパフォーマンス"
 SETTING_ANISOTROPIC_FILTERING: "テクスチャフィルタリング"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!アニソトロピックフィルタリングはテクスチャの表面の見た目を良くします。\n\n低く設定するとパフォーマンスが向上します。"
 SETTING_RESOLUTION: "解像度"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!ゲームのイメージの品質を決定します。\n\n低解像度はパフォーマンスを向上させる場合があります。\n\n#X サポートしていなアスペクト比のゲーム解像度は、インターフェイスをスクリーンの外にはみ出させｒる場合があります。"
 SETTING_WINDOWED_RESOLUTION: "ウィンドウ解像度"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!ウィンドウモードのゲームの解像度を決定します。\n\n#b 数字#!x#b 数字#!の形式である必要があります。\n\n#X サポートしていないアスペクト比のゲーム解像度は、インターフェイスをスクリーン外にはみ出させる場合があります。#!"
 SETTING_RENDER_SCALE: "レンダラースケール"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nユーザーインターフェイスを除く、主な解像度に対するゲームのレンダー解像度の尺度です。\n\n低く設定するとパフォーマンスが向上する場合がありますが、全体的な忠実性が減少し、100%以上に設定すると忠実性は上がりますが、パフォーマンスが下がる可能性があります。"
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "モニター"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!複数のモニターを使用する場合、ゲームに使用するモニターを選択します。"
 SETTING_GRAPHICS_DEVICE: "グラフィックカード"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!ゲームが使用するグラフィックカードを選択します。\n\n統合グラフィックカードまたはソフトウェアレンダラーを使用するとパフォーマンスが下がる場合があります。"
 SETTING_SHADOW_MAP_RESOLUTION: "シャドー品質"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!シャドーが有効化されている場合、シャドーマップがレンダリングされる解像度を決定します。\n\n低く設定するとパフォーマンスが向上する場合があります。"
 SETTING_DISPLAY_MODE: "ディスプレイモード"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!ゲームをスクリーンにどのように表示するかを決定します"
 SETTING_BLOOM_QUALITY: "ブルーム"
 SETTING_MESH_LOD_BIAS: "メッシュLOD品質"
 SETTING_MESH_LOD_FADE: "メッシュLODフェード"
 SETTING_TERRAIN_SMOOTHING: "地形スムージング"
 OPTION_FULLSCREEN: "フルスクリーン"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!ゲームを全画面に表示します。解像度によりイメージのシャープさが変わります。"
 OPTION_WINDOWED: "ウィンドウ"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!ゲームをウィンドウに表示します。解像度によりウィンドウのサイズが変わります。"
 OPTION_DISABLED: "無効"
 OPTION_OFF: "オフ"
 OPTION_LOW: "低"
 OPTION_MEDIUM: "中"
 OPTION_HIGH: "高"
 OPTION_ULTRA: "ウルトラ"
 OPTION_CUSTOM: "カスタム"
 OPTION_DEFAULT: "デフォルト"
 SETTINGS_CATEGORY_UI: "インターフェイス"
 SETTINGS_CATEGORY_GAME: "ゲーム"
 SETTING_TEXTURE_QUALITY: "テクスチャ品質"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nロードされたテクスチャの解像度をコントロールします。\n\n低く設定するとパフォーマンスが向上する場合があります。"
 SETTING_QUALITY: "品質プリセット"
 SETTING_SFX: "SFX"
 SETTING_UI: "インターフェイス"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!下の詳細グラフィックオプションのプリセットを選択します。\n\n低いプリセットはパフォーマンスが向上します。"
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!ブルーム効果を有効にします。これは画像にとても明るい光があふれ出ているように見える演出です。\n\n設定を下げるとパフォーマンスが向上します。"
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!被写界深度を有効にしてカメラレンズをシミュレートし、イメージのフォーカスから外れたポイントをぼかします。\n\nオフにするとパフォーマンスが向上する場合があります。"
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!ブルームが多いエリアで出現するレンズフレアを有効にします。エフェクトを表示するにはブルームを有効にする必要があります。\n\nオフにするとパフォーマンスが向上する場合があります。"
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!ブルームが多いエリアで出現する二次レンズフレアを有効にします。エフェクトを表示するにはブルームを有効にする必要があります。\n\nオフにするとパフォーマンスが向上する場合があります。"
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!スクリーンスペース・アンビエント・オクルージョンをマップに適用するかどうかを決定します。\n\nオフにするとパフォーマンスが向上する場合があります。"
 SETTING_REFRACTION_TOOLTIP: "水面に屈折が現れるかどうかを決定します。"
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\n水面屈折が有効化されている場合の品質をコントロールします。\n\n低く設定するとパフォーマンスが向上する場合があります。"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nマップオブジェクト（建物など）の最高品質レベルを決定します。\n\n低く設定するとパフォーマンスが向上する場合があります。"
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nユニットモデルなどのマップオブジェクトのLOD（ディテールのレベル）の品質を決定します。\n\n低く設定するとパフォーマンスが向上する場合があります。"
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!オンにすると、ズームインまたはアウトした際に3Dモデルが様々なディテールのレベル（LOD）間をスムーズに移行します。\n\nオフにするとパフォーマンスが向上する場合があります。"
 SETTING_PROVINCE_NAMES_TOOLTIP: "都市と地方の名前がマップ上にどのように表示されるかを決定します。"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "マップ上の国境に通過不可の地形を含むかどうかを決定します。"
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nユーザーインターフェイスの言語を決定します。"
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "あなたのParadoxアカウントのメールアドレス"
 SETTING_FRAMERATE_CAP: "最大FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nゲームがレンダリングする最大FPS（1秒当たりのフレーム数）です。\n\n低く設定すると電力消費を抑える場合があります。"
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "テクスチャストリーミング"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nテクスチャが必要に応じて読み込まれます。\n\nCPUのオーバーヘッド時間のいくらかを代償にGPUメモリの使用量を低下させます。少量のメモリによりGPUのパフォーマンスが向上する可能性があります。"
 SETTING_TEXTURE_STREAMING_CACHE: "テクスチャストリーミングキャッシュサイズ"
 SETTING_VALUE_MB: "$VALUE$MB"
 #GUI
 SETTING_ANIMATION_SPEED: "アニメーション速度"
 SETTING_GUI_SCALING: "GUIスケーリング"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!ユーザーインターフェイス全体のスケールを設定します。高解像度の画面に便利です。\n\n#X 高く設定し過ぎると、インターフェイスが画面に収まらない場合があります！#!"
 SETTING_TOOLS_GUI_SCALING: "工具GUIスケーリング"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!工具ユーザーインターフェースのスケールを設定します。画面解像度が高いほど効果が現れます。\n\n#X あまり高く設定し過ぎると、UIが画面におさまりきらなくなる場合があります！#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "マウスパン"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "フリー"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8方向"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "無効"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nマウスでパンした時のカメラの挙動です。"
 SETTING_SCROLL_SPEED: "パン速度"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nキーボードまたはマウスを使用した時にマップがパンする速度を設定します。"
 SETTING_CAMERA_ROTATION_SPEED: "カメラ回転速度"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nカメラの回転速度です。"
 SETTING_ZOOM_SPEED: "ズーム速度"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nカメラのズーム速度です。"
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "ズーム挙動"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "相対カーソル"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "カーソルにズームイン"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "カーソルを無視"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nズームイン・アウト時のマウスカーソルに対するカメラの挙動です。"
 SETTING_INPUT_DEVICE: "入力デバイス"
 SETTING_EDITOR: "エディター"
 SETTING_EDITOR_POSTFIX: "エディターポストフィックス"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "エディターオープンコマンド"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "ログコマンド確認"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "コードエディターオープンコマンド"
 SETTING_GRACEFUL_EXIT: "優雅な退出"
 SETTING_LANGUAGE: "言語"
 MOUSE_AND_KEYBOARD: "マウスとキーボード"
 GAMEPAD: "ゲームパッド"
 SETTING_MULTISAMPLING_DISABLED: "無効"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "無効"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "無効"
 #Editor
 SETTING_CAMERA_TILT: "カメラチルト"
 SETTING_CAMERA_STRATEGY: "カメラタイプ"
 SETTING_CENTERED_ZOOM_IN: "カメラズームイン"
 SETTING_CAMERA_SPEED: "カメラ速度"
 CAMERA_TABLETOP: "テーブルトップ"
 CAMERA_FPS: "一人称"
 CAMERA_WASD: "WASDスタイル"
 #Audio
 SETTING_Music: "音楽"
 SETTING_Ambient: "環境音楽"
 SETTING_Effects: "効果"
 SETTING_Master: "マスター"
 SETTING_VO: "ボイスオーバー"
 SETTING_VO_TOOLTIP: "#T ボイスオーバーの音量\n#!ゲーム内でのボイスオーバーの音量を設定します。"
 SETTING_Master_TOOLTIP: "#T マスター音量\n#!ゲーム内のすべての音量を設定します。"
 SETTING_Music_TOOLTIP: "#T 音楽の音量\n#!音楽の音量を設定します。"
 SETTING_Ambient_TOOLTIP: "#T 環境音楽の音量\n#!環境音楽の音量を設定します。"
 SETTING_SFX_TOOLTIP: "#T 特殊効果の音量\n#!戦闘時等の特殊効果の音量を設定します。"
 SETTING_UI_TOOLTIP: "#T インターフェイスの音量\n#!ユーザーインターフェイスの音量を設定します。"
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "デバッグログレベル"
 SETTING_AUDIO_DEVICE_PROFILE: "オーディオプロフィール"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!あなたのセットアップに適したオーディオプロフィールを選択します。"
 SETTING_AUDIO_OPTION_SPEAKERS: "スピーカー"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!$SETTING_AUDIO_OPTION_SPEAKERS$のデフォルトミックスです。"
 SETTING_AUDIO_OPTION_HEADPHONES: "ヘッドフォン"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!$SETTING_AUDIO_OPTION_HEADPHONES$のために調整されたミックスです。"
 SETTING_AUDIO_OPTION_TV: "テレビ"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!$SETTING_AUDIO_OPTION_TV$とモニタースピーカーのためのミックスです。"
 SETTING_AUDIO_OPTION_NIGHTMODE: "ナイトモード"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!夜間のプレイのために音を柔らかくし、高ピッチを弱くしてダイナミックレンジを圧縮します。"
 SETTING_MUSIC_DENSITY: "音楽密度"
 SETTING_MUSIC_DENSITY_TOOLTIP: "静寂、ムード音楽といったセグメント間のバランスをコントロールします\n\n強烈 -`ラジオ放送局'のように大半の楽曲を順次演奏します \n調和 - 楽曲、静寂、ムード音楽の設定のバランスが完璧に調整されています\nリラックス - 大半がリラックスできる音楽セグメントで構成され、よりムードのある視聴体験となります。数時間連続視聴しても周回していることがそれほど気になりません」"
 #Game
 SETTING_AUTOSAVE: "オートセーブの間隔"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!ゲームが自動セーブを行う頻度を設定します。"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "オートセーブをクラウドに保存するかどうかを決定します。"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "カメラが常に北を向くか向かないかを決定します。"
 NO_AUTOSAVE: "オートセーブなし"
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "ファイル転送速度"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!マルチプレイロビーでセーブファイルを転送する最高速度を設定します。\n\n低く設定すると、マルチプレイゲーム参加時のネットワークの安定性が向上しますが、マルチプレイロード時間に悪影響を与えます。"
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "マップエディターオードセーブ（分）"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "マップエディターオードセーブ間隔（分）"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "ノードエディタードラッグパンモード"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "アクセシビリティ"
 SETTING_COLOR_BLIND_MODE: "色弱モード"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!ゲーム全体のテキストに使用されている色を、様々なタイプの色弱者が認知しやすい色のセットに変更します。"
