l_japanese:
 SETTING_AUTOSAVE_TO_CLOUD: "クラウドにオートセーブ"
 SETTING_SAVE_FILE_FORMAT: "デフォルトセーブ形式"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "このオプションはアイアンマン、クラウド、デバッグモードで上書きされます"
 OPTION_SAVE_FILE_TEXT: "テキスト"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "ZIPテキスト"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "ZIPバイナリ"
 SETTING_TOOLTIP_MODE: "ツールチップモード"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nツールチップのロック方法を選択します:\n   #b マウス挙動#!ツールチップにカーソルを移動させるとロックします。\n   #b タイマーロック#!一定時間が経過するとロックします。\n   #b アクションロック#!マウスの中ボタンでロックします。\n   #b タイマーかアクションロック#! - タイマーロックまたはアクションロックを使用できます。"
 SETTING_TOOLTIP_MODE_NO_LOCK: "ロックなし"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "マウス性質"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "アクションロック（マウスアンカー）"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "タイマーロック（マウスアンカー）"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "アクションロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "タイマーロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "タイマーかアクションロック"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nツールチップを備えたエレメントにマウスオーバーした際の表示遅延を設定します。"
 SETTING_TOOLTIP_DELAY: "遅延表示"
 SETTING_TOOLTIP_UNLOCK_TIME: "遅延ロック解除"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nツールチップのロックが解除されるまでの時間を設定します。"
 SETTING_TOOLTIP_LOCK_TIME: "遅延ロック"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nツールチップがロックされるまでの時間を設定します。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "遅延ロックオープン"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n他のツールチップがすでに開いているときに、ツールチップがロックされるまでの時間を設定します。"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "上級"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "一般"
 SETTINGS_CATEGORY_SFX: "効果音"
 SETTINGS_CATEGORY_MFX: "音楽"
 SETTINGS_CATEGORY_LANGUAGE: "言語"
 SETTINGS_CATEGORY_SAVE_GAMES: "ゲームをセーブ"
 SETTINGS_CATEGORY_TOOLTIPS: "ツールチップ設定"
 SETTINGS_CATEGORY_MAP_CONTROLS: "マップ操作"
 SETTINGS_CATEGORY_MAPMODES: "マップモード"
 SETTING_SHADER_QUALITY: "シェーダー品質"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T シェーダー品質\n#!各種シェーダーやエフェクトの品質を決定します。\n\n#T 高：#! パフォーマンスを犠牲にして一部のシェーダーエフェクトの品質を向上させます。\n\n#T 中#! 意図したグラフィック体験のためのデフォルト設定です。\n\n#T 低#! この設定はローエンドのマシン用に作られており、ビジュアル品質が低下するため推奨されません。複数のシェーダーを簡略化して、グラフィックパフォーマンスを向上させます。"
 SETTING_SHOW_NUDITY: "裸体表示"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nキャラクターの裸体を表示するかどうかを設定します。"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "ポートレート"
 SETTING_SOUNDTRACK: "BGM"
 SETTING_SOUNDTRACK_TOOLTIP: "BGM全般"
 SETTING_MUSIC_STINGERS: "スティンガー曲"
 SETTING_MUSIC_STINGERS_TOOLTIP: "ゲームプレイを盛り上げる短い音楽のフレーズ"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "音楽"
 SETTING_AMBIENT: "環境音楽"
 SETTING_MUSIC_TOOLTIP: "#T 音楽の音量\n#!音楽の音量を設定します。"
 SETTING_AMBIENT_TOOLTIP: "#T 環境音楽の音量\n#!環境音楽の音量を設定します。"
 SETTING_MAP_TOOLTIP_DELAY: "マップのツールチップの遅延"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nマップのツールチップが表示されるまでの時間を表示します。"
 SETTING_MAP_MODE_DELAY: "マップモードの遅延"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "新しいマップモードに切り替えるまでの遅延（秒単位）"
 SETTING_MAP_MODE_FADE_IN: "マップモードのフェードイン"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "古いマップモードがフェードアウトした後、新しいマップモードがフェードインする時間（秒単位）"
 SETTING_MAP_MODE_FADE_OUT: "マップモードのフェードアウト"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "新しいマップモードが適用された際、マップモードの遅延の後に現在のマップモードがフェードアウトする時間（秒単位）"
 SETTING_OCCUPATION_STRIPES: "縞模様の占領ビジュアル"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\n地図上の占領ビジュアルとして、国旗テクスチャの代わりに色付きの縞模様を使用するようにします。"
 color_blind_mode_test: "テスト"
